### ISSUE TITLE
CSL-M in Pandoc

### ISSUE THREAD

**Issue by demai** [cormacrelf/citeproc-rs#2]
This project looks very promising. Are there plans for making CSL-M extensions available with pandoc? Would be amazing. (I am especially keen on using things like `hereinafter` or the classic item type.)

**Comment by cormacrelf** [comment]
Yes, that’s one of the main reasons I started building it. It may not end up as two separate standards, ideally all the extensions in CSL-M will just be opt-in feature flags for edge users and we can slowly stabilise them.

**Comment by demai** [comment]
Awesome! I am really looking forward to when we can start using citeproc-rs.

**Comment by cormacrelf** [comment]
Closing because you can already track status on the other issue.
