### ISSUE TITLE
Cannot build citeproc-db with `cargo vendor`

### ISSUE THREAD

**Issue by MetaDark** [cormacrelf/citeproc-rs#23]
@doronbehar and I maintain [texlab for the Nix package manager](https://github.com/NixOS/nixpkgs/blob/f3402a38dacb56f3c6145bb8cabd087efa3e5e90/pkgs/development/tools/misc/texlab/default.nix) and I've encountered the following error trying to build 1.8.0 (which now uses citeproc-rs):

```
error: couldn't read /tmp/nix/texlab/texlab-1.8.0-vendor/citeproc-db/src/../../wasm/src/locales-en-US.xml: No such file or directory (o
s error 2)                                                                                                                            
   --> /tmp/nix/texlab/texlab-1.8.0-vendor/citeproc-db/src/xml.rs:320:13
    |
320 |             include_str!("../../wasm/src/locales-en-US.xml").to_string(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```
This seems to be an issue with `citeproc-db` depending on `locales-en-US.xml` in `citeproc-wasm`.  

For a normal run of `cargo build` this isn't an issue, but if the dependencies are vendored prior to running `cargo build`, `citeproc-db` will be compiled independently from `citeproc-wasm`, and it won't find `locales-en-US.xml`.

This can be reproduced by:
- Setting the working directory to the texlab repo
- Running `cargo vendor`
- Following the instructions displayed in the output, for example:
```
To use vendored sources, add this to your .cargo/config for this project:

[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/cormacrelf/citeproc-rs"]
git = "https://github.com/cormacrelf/citeproc-rs"
rev = "796ea0382392ae1befdc39f21162ed83b640ac29"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/tmp/texlab/vendor"
```
- Running `cargo build`

**Comment by doronbehar** [comment]
@MetaDark is this an issue with texlab 1.9.0 as well?

**Comment by MetaDark** [comment]
@doronbehar Yes, the dependency on citeproc was refactored into [separate crate](https://github.com/latex-lsp/texlab/blob/master/crates/texlab_citeproc/Cargo.toml) in texlab, and it's still a problem.
