### ISSUE TITLE
Publish prerelease builds of the wasm driver

### ISSUE THREAD

**Issue by cormacrelf** [cormacrelf/citeproc-rs#7]
It takes a while to build and is tricky to link in to browser JS projects. A better way would be to publish alpha releases on NPM. It does need a package name first.

* `citeproc-wasm`?
* `@citeproc-rs/driver`?

Then a travis script to publish for any PRs merged into master.

**Comment by chriskrycho** [comment]
Maybe, given the aspirations of the project, `@citeproc/wasm-driver`? This is bikeshed territory for sure! But if `@citeproc` is available that’d be :100:

**Comment by cormacrelf** [comment]
https://discourse.citationstyles.org/t/bundled-citation-styles-and-processor/1564/38

For sure it has to distinguish from `citeproc` on NPM AKA the citeproc-js project. I’m rethinking not suggesting a -js scope in that thread.

**Comment by chriskrycho** [comment]
Ah, that makes sense. I can offer this as a suggestion over there as well, but perhaps people would be amenable to `@citeproc` as an umbrella for all of these packages?

**Comment by cormacrelf** [comment]
There aren’t that many, and I think the value is in related ones looking like they’re together. The rest of the (many) citeprocs out there can never be published to NPM anyway. It was noted in that thread that the convention is `citeproc-lang`.

**Comment by chriskrycho** [comment]
Ah, fair enough!

**Comment by cormacrelf** [comment]
Closed in #65
