### ISSUE TITLE
previewCitationCluster() is broken

### ISSUE THREAD

**Issue by adomasven** [cormacrelf/citeproc-rs#89]
Used to have to provide an item with `{id: 0}` for the citation, and in citation order array, but now i'm just providing an empty object instead (not a note item) as per updated instructions, and getting back 

> ()

as output with APA. Can we have some tests for this method?

**Comment by cormacrelf** [comment]
I have it tested pretty comprehensively on the Rust side, but I haven't got a JS smoke test. I might have changed the API for the first argument as well though (sorry), and in my my zotero-client patches I had to change the first argument from a `Cluster` with a useless id, to just the cites array. The current docs do reflect this.

**Comment by adomasven** [comment]
Oh yeah, this works fine. I didn't realize the signature of the first parameter had changed. Thanks
