### ISSUE TITLE
driver.free() is undefined

### ISSUE THREAD

**Issue by adomasven** [cormacrelf/citeproc-rs#98]
The canary build does not have a defined `driver.free()` method.

**Comment by cormacrelf** [comment]
Can you give more details on this? The method is definitely defined on the Driver class.


![image](https://user-images.githubusercontent.com/378760/101495637-ded3f600-39bc-11eb-9882-ac4f10cef446.png)

**Comment by adomasven** [comment]
Sorry, this is my bad in not unwrapping the `Driver.new()` call and trying to use it like a Driver instance.

**Comment by cormacrelf** [comment]
Yeah the unwrap is awful isn't it, sorry. You'll be able delete them again tomorrow.
